CREATE TABLE [SOP_Version_20171208_154148] (
  [EffectiveDate] DOUBLE ,
  ['100-Rapid assessment'] CURRENCY ,
  ['101-BLCA field methods'] CURRENCY ,
  ['102-DINO field methods'] CURRENCY ,
  ['103-CANY field methods'] CURRENCY ,
  ['104-DINO measuring vegetation'] CURRENCY ,
  ['105-DINO facies mapping & grain size dist_'] CURRENCY ,
  ['106-CANY & DINO equip_ lists'] CURRENCY ,
  ['107-CANY field methods'] CURRENCY ,
  ['10-After each field season'] CURRENCY ,
  ['11-Data management'] CURRENCY ,
  ['12-Data analysis & reporting'] CURRENCY ,
  ['13-Revising the protocol'] CURRENCY ,
  ['14-BLCA field methods'] CURRENCY ,
  ['DINO sentinel site set up'] CURRENCY ,
  ['14-Facies mapping'] CURRENCY ,
  ['15-CURE methods'] CURRENCY ,
  ['16-Total station surveying'] CURRENCY ,
  ['17-RTK surveying part 1'] CURRENCY ,
  ['18-RTK surveying part 2'] CURRENCY ,
  ['19-Remote sensing'] CURRENCY ,
  ['1-Prior to field season/equip_ lists'] CURRENCY ,
  ['20-CURE field methods'] CURRENCY ,
  ['2-Training observers'] CURRENCY ,
  ['3-GPS methods'] CURRENCY ,
  ['4-Sentinel site set up'] CURRENCY ,
  ['5-Photos'] CURRENCY ,
  ['6-Measuring vegetation'] CURRENCY ,
  ['6-Vegetation'] CURRENCY ,
  ['7-Hydrologic measurements'] CURRENCY ,
  ['8-Facies mapping & grain size dist_'] CURRENCY ,
  ['8-Surveying'] CURRENCY ,
  ['9-After each field visit'] CURRENCY ,
  [''] CURRENCY 
)
