CREATE TABLE [tbl_wrk_Route_Species] (
  [Unit_Code] VARCHAR (4),
  [Visit_Year] SHORT ,
  [Species] VARCHAR (50),
  [Common_Name] VARCHAR (50),
  [Big Fill Section County Road(10)PlotCount] SHORT ,
  [Big Fill Section County Road(10)CoverPct] DOUBLE ,
  [Big Fill Section County Road(10) (SE)] DOUBLE ,
  [County Road(4)PlotCount] SHORT ,
  [County Road(4)CoverPct] DOUBLE ,
  [County Road(4) (SE)] DOUBLE ,
  [East Tour Road(10)PlotCount] SHORT ,
  [East Tour Road(10)CoverPct] DOUBLE ,
  [East Tour Road(10) (SE)] DOUBLE ,
  [Facility Road(1)PlotCount] SHORT ,
  [Facility Road(1)CoverPct] DOUBLE ,
  [Facility Road(1) (SE)] DOUBLE ,
  [Hydro 1(1)PlotCount] SHORT ,
  [Hydro 1(1)CoverPct] DOUBLE ,
  [Hydro 1(1) (SE)] DOUBLE ,
  [Last Cut Drainage(4)PlotCount] SHORT ,
  [Last Cut Drainage(4)CoverPct] DOUBLE ,
  [Last Cut Drainage(4) (SE)] DOUBLE ,
  [Pacific Track Grade(2)PlotCount] SHORT ,
  [Pacific Track Grade(2)CoverPct] DOUBLE ,
  [Pacific Track Grade(2) (SE)] DOUBLE ,
  [Polsoms Road(4)PlotCount] SHORT ,
  [Polsoms Road(4)CoverPct] DOUBLE ,
  [Polsoms Road(4) (SE)] DOUBLE ,
  [Residence Service Road(1)PlotCount] SHORT ,
  [Residence Service Road(1)CoverPct] DOUBLE ,
  [Residence Service Road(1) (SE)] DOUBLE ,
  [Water Tank Road(1)PlotCount] SHORT ,
  [Water Tank Road(1)CoverPct] DOUBLE ,
  [Water Tank Road(1) (SE)] DOUBLE ,
  [Witkers Service Road(1)PlotCount] SHORT ,
  [Witkers Service Road(1)CoverPct] DOUBLE ,
  [Witkers Service Road(1) (SE)] DOUBLE 
)
