CREATE TABLE [UnknownSpecies] (
  [ID] AUTOINCREMENT,
  [Unknown_ID] VARCHAR (50),
  [UnknownCode] VARCHAR (15) CONSTRAINT [UnknownCode] UNIQUE ,
  [CollectedBy_ID] SHORT ,
  [Method] VARCHAR (50),
  [Transect_Number] SHORT ,
  [PlantType] VARCHAR (50),
  [PlantDescription] LONGTEXT ,
  [SalientFeature] VARCHAR (255),
  [LeafType] VARCHAR (50),
  [Margin] VARCHAR (50),
  [OtherCharacteristics] VARCHAR (255),
  [StemCharacteristics] VARCHAR (255),
  [FlowerCharacteristics] VARCHAR (255),
  [GeneralCharacteristics] VARCHAR (255),
  [Collected] BYTE ,
  [BestGuess] VARCHAR (50),
  [ConfirmedCode] VARCHAR (50),
  [HasPhotos] BYTE ,
  [ForbGrassType] VARCHAR (10),
  [PerennialGrasses] VARCHAR (15),
  [IdentifiedBy_ID] SHORT ,
  [IdentifiedDate] DATETIME ,
  [Position] SHORT 
)
