CREATE TABLE [xtbl_Unknown_Species] (
  [Unknown_ID] VARCHAR (50),
  [Species_ID] VARCHAR (50),
  [Unknown_Code] VARCHAR (15) CONSTRAINT [UnknownCode] UNIQUE ,
  [Collected_by] VARCHAR (50),
  [Method] VARCHAR (50),
  [Transect_Number] SHORT ,
  [Plant_Type] VARCHAR (50),
  [Plant_Description] LONGTEXT ,
  [Salient_Feature] VARCHAR (255),
  [Leaf_Type] VARCHAR (50),
  [Margin] VARCHAR (50),
  [Other_Characteristics] VARCHAR (255),
  [Stem_Characteristics] VARCHAR (255),
  [Flower_Characteristics] VARCHAR (255),
  [General_Characteristics] VARCHAR (255),
  [Collected] VARCHAR ,
  [Best_Guess] VARCHAR (50),
  [Confirmed_Code] VARCHAR (50),
  [Have_Photos] VARCHAR ,
  [Forb_Grass_Type] VARCHAR (10),
  [Perennial_Grasses] VARCHAR (15),
  [Identified_by] VARCHAR (50),
  [Identified_Date] DATETIME ,
  [Position] SHORT 
)
