dbMemo "SQL" ="PARAMETERS EID Long, SID Long, FID Long, TID Long, MSSID Long, pnum Long, pdist "
    "Long, pctfines IEEEDouble, pctwater IEEEDouble, pctlitter IEEEDouble, pctwd IEEE"
    "Double, pctsd IEEEDouble, pctfa IEEEDouble, pctmss IEEEDouble, pctwcc IEEEDouble"
    ", pcturc IEEEDouble, pctarc IEEEDouble, pd Long, nocanopy Byte, norooted Byte, h"
    "astrails Byte, noindsp Byte, cplot Byte, rplot Byte;\015\012INSERT INTO VegPlot "
    "( Event_ID, Site_ID, Feature_ID, VegTransect_ID, ModalSedimentSize_ID, PlotNumbe"
    "r, PlotDistance_m, PctFines, PctWater, PctLitter, PctWoodyDebris, PctFilamentous"
    "Algae, PctStandingDead, PctModalSedimentSize, WoodyCanopyPctCover, UnderstoryRoo"
    "tedPctCover, AllRootedPctCover, PlotDensity, NoCanopyVeg, NoRootedVeg, HasSocial"
    "Trails, NoIndicatorSpecies, CalibrationPlot, ReplicatePlot )\015\012VALUES ([EID"
    "], [SID], [FID], [TID], [MSSID], [pnum], [pdist], [pctfines], [pctwater], [pctli"
    "tter], [pctwd], [pctfa], [pctsd], [pctmss], [pctwcc], [pcturc], [pctarc], [pd], "
    "[nocanopy], [norooted], [hastrails], [noindsp], [cplot], [rplot]);\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
Begin
End
