dbMemo "SQL" ="PARAMETERS pkcode Text ( 4 ), waterway Text ( 25 );\015\012SELECT DISTINCT s.ID,"
    " s.SiteCode, s.SiteName, s.SiteName + ' (' + s.SiteCode + ')' AS Site\015\012FRO"
    "M (Site AS s INNER JOIN Park AS p ON s.Park_ID = p.ID) INNER JOIN River AS r ON "
    "r.ID = s.River_ID\015\012WHERE p.ParkCode = [pkcode]\015\012AND r.River = [water"
    "way];\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
Begin
End
