dbMemo "SQL" ="PARAMETERS appuser Text ( 50 );\015\012SELECT c.ID, LastName +',  '+ FirstName +"
    " ' ('+ Username +')' AS AppUser, AccessLevel, IsActive, ca.Access_ID AS AccessLe"
    "velID\015\012FROM (Contact AS c INNER JOIN Contact_Access AS ca ON ca.Contact_ID"
    " = c.ID) INNER JOIN Access AS a ON a.ID = ca.Access_ID\015\012WHERE Username = ["
    "appuser];\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
Begin
End
